# Generated by Django 4.2.2 on 2023-08-28 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('type', models.IntegerField(choices=[(1, 'Jewellery'), (2, 'Skin care'), (3, 'Vintage')])),
                ('image', models.ImageField(upload_to='uploads/')),
                ('is_new_arrival', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
            ],
        ),
    ]
