# Generated by Django 4.2.2 on 2023-08-28 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_cart_productincart_cart_products'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productincart',
            unique_together={('cart', 'product')},
        ),
    ]
